version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    ports:
      - "3306:3306"
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: funilaria
      MYSQL_USER: funileiro
      MYSQL_PASSWORD: funileiro123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  node:
    image: node:20.12.2
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - /var/www/html/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    ports:
      - "5174:5174"
    depends_on:
      - app
    networks:
      - laravel


networks:
  laravel:
    driver: bridge

volumes:
  mysql-data: